import path from "node:path";

import { openai } from "@ai-sdk/openai";
import { ToolLoopAgent, stepCountIs, type InferAgentUIMessage } from "ai";
import {
  experimental_createSkillTool as createSkillTool,
  createBashTool,
} from "bash-tool";

import { INCIDENTS_PER_RUNBOOK, SYSTEM_PROMPT } from "./context";
import { RUNBOOKS, generateIncidentArchive } from "./runbooks";

// Easy to change: defaults to gpt-5-mini, override with OPENAI_MODEL. (We keep
// OpenAI for workshop consistency with issue-triage / issue-triage-2x — bash-tool
// is model-agnostic, so the same skills would work behind any AI SDK model.)
const MODEL = process.env.OPENAI_MODEL ?? "gpt-5-mini";

// The committed skill pack: skills/<rb-id>/SKILL.md, generated by
// scripts/build-skills.ts. The skill loader reads SKILL.md from disk at call time,
// so the directory must exist where the server runs (it's committed) and the route
// must be the Node runtime (see app/api/chat/route.ts).
const SKILLS_DIR = path.join(process.cwd(), "skills");

/**
 * Build the triage agent — the heart of the "after" demo.
 *
 * Where issue-triage-2x dumped all 18 runbooks + 180 incidents into the system
 * prompt, this agent carries a THIN prompt and reaches for knowledge on demand:
 *
 *   - `skill`  — bash-tool's skill loader. Its auto-generated description is the
 *                always-on INDEX (one `skill("rb-…"): <when to use>` line per
 *                runbook). Calling it returns that one runbook's full body.
 *   - `bash`   — runs in a local just-bash sandbox (no Vercel account). We mount
 *                the incident archive as a file here so the model can grep it
 *                instead of carrying 180 entries in context.
 *
 * `ToolLoopAgent` runs the model → tool → result loop for us, exactly like the
 * tiny CLI agent's hand-written loop, declared once.
 */
async function buildAgent() {
  // Discover the 18 runbook skills from disk. `skillFiles` is every SKILL.md as a
  // path→content map; `instructions` is the "SKILL DIRECTORIES" note for bash.
  const { skill, files: skillFiles, instructions } = await createSkillTool({
    skillsDirectory: SKILLS_DIR,
  });

  // The incident archive is NOT in the prompt. Mount it as a file the bash tool
  // can grep on demand — it costs ~0 context tokens until the model looks.
  const incidentCount = RUNBOOKS.length * INCIDENTS_PER_RUNBOOK;
  const files = {
    ...skillFiles,
    "incidents.md": generateIncidentArchive(INCIDENTS_PER_RUNBOOK),
  };

  const extraInstructions =
    `${instructions}\n\n` +
    `INCIDENT ARCHIVE:\n` +
    `A full incident history (${incidentCount} entries) is in your working ` +
    `directory as incidents.md, and is NOT in your context. Grep it for precedent ` +
    `(e.g. \`grep -i "RB-CHK-02" incidents.md\`) instead of guessing.`;

  const { tools } = await createBashTool({ files, extraInstructions });

  return new ToolLoopAgent({
    model: openai(MODEL),
    instructions: SYSTEM_PROMPT,
    tools: { skill, bash: tools.bash },
    // Headroom for: pick → load one or two skills → optional grep → compose.
    stopWhen: stepCountIs(8),
    // gpt-5* are reasoning models; ask for a reasoning summary so the UI can show
    // a "Thinking…" panel. No reasoningEffort override — the default keeps the
    // agent robust, which is the whole point of the "after".
    providerOptions: { openai: { reasoningSummary: "auto" } },
  });
}

// Constructing the toolkit reads the skills dir and spins up just-bash, so do it
// ONCE per server process and await the same promise on every request.
let agentPromise: Promise<Awaited<ReturnType<typeof buildAgent>>> | undefined;
export function getTriageAgent() {
  return (agentPromise ??= buildAgent());
}

/** The agent's type — the basis for the typed UI message below. */
export type TriageAgent = Awaited<ReturnType<typeof buildAgent>>;

/**
 * End-to-end type safety: the UI message — including the typed `tool-skill` /
 * `tool-bash` parts — is inferred straight from the agent. The client types
 * `useChat` with this via chat-types.ts (which layers on the token-usage metadata
 * the ContextMeter reads).
 */
export type TriageUIMessage = InferAgentUIMessage<TriageAgent>;
