import path from "node:path";

import { openai } from "@ai-sdk/openai";
import { ToolLoopAgent, stepCountIs, type InferAgentUIMessage } from "ai";
import {
  experimental_createSkillTool as createSkillTool,
  createBashTool,
} from "bash-tool";

import { INCIDENTS_PER_RUNBOOK, SYSTEM_PROMPT } from "./context";
import { RUNBOOKS, generateIncidentArchive } from "./runbooks";

// Easy to change: defaults to gpt-5-mini, override with OPENAI_MODEL. (We keep
// OpenAI for workshop consistency with issue-triage / issue-triage-2x — bash-tool
// is model-agnostic, so the same skills would work behind any AI SDK model.)
const MODEL = process.env.OPENAI_MODEL ?? "gpt-5-mini";

// The same "reasoning effort" dial issue-triage-2x uses. Unset = the model's normal
// reasoning (robust). Set OPENAI_REASONING_EFFORT=minimal (or "low") to strip the
// safety net. The point of having it HERE is the A/B: 2x drifts on "minimal" because
// it must reason over ~14k of bloat; this app keeps the prompt thin and loads only
// the runbook it needs, so it should still hold R1–R5 on "minimal" — the lesson being
// that the fix is less context, not more reasoning. Read at module load; restart the
// dev server after changing it.
const REASONING_EFFORT = process.env.OPENAI_REASONING_EFFORT;

// The committed skill pack: skills/<rb-id>/SKILL.md, generated by
// scripts/build-skills.ts. The skill loader reads SKILL.md from disk at call time,
// so the directory must exist where the server runs (it's committed) and the route
// must be the Node runtime (see app/api/chat/route.ts).
const SKILLS_DIR = path.join(process.cwd(), "skills");

/**
 * Build the triage agent — the heart of the "after" demo.
 *
 * Where issue-triage-2x dumped all 18 runbooks + 180 incidents into the system
 * prompt, this agent carries a THIN prompt and reaches for knowledge on demand:
 *
 *   - `skill`  — bash-tool's skill loader. Its auto-generated description is the
 *                always-on INDEX (one `skill("rb-…"): <when to use>` line per
 *                runbook). Calling it returns that one runbook's full body.
 *   - `bash`   — runs in a local just-bash sandbox (no Vercel account). We mount
 *                the incident archive as a file here so the model can grep it
 *                instead of carrying 180 entries in context.
 *
 * `ToolLoopAgent` runs the model → tool → result loop for us, exactly like the
 * tiny CLI agent's hand-written loop, declared once.
 */
async function buildAgent() {
  // 🛠️ ──────────────────────────────────────────────────────────────────────
  // WORKSHOP TODO — wire the agent's TOOLS (skill + bash, via bash-tool)
  //
  // Right now this returns a tool-LESS agent: it has the thin prompt but no way to
  // load a runbook or grep incidents, so it can't actually triage. Build the
  // toolkit — the heart of the "after" demo:
  //
  //   1. Discover the skills on disk:
  //        const { skill, files: skillFiles, instructions } =
  //          await createSkillTool({ skillsDirectory: SKILLS_DIR });
  //      → `skill`'s auto-generated description IS the always-on index; `skillFiles`
  //        is every SKILL.md as a path→content map.
  //      (Run `npm run build:skills` first — skills/ is generated, see build-skills.ts.)
  //   2. Mount the incident archive as a FILE, not in the prompt:
  //        const files = { ...skillFiles,
  //          "incidents.md": generateIncidentArchive(INCIDENTS_PER_RUNBOOK) };
  //      and extend `instructions` to tell the model to grep ./incidents.md.
  //   3. Spin up the local just-bash sandbox (no Vercel account):
  //        const { tools } = await createBashTool({ files, extraInstructions });
  //   4. Hand the model BOTH tools:
  //        tools: { skill, bash: tools.bash }
  //
  // 💡 Budget enough steps (stepCountIs): on low reasoning effort the model loads
  //    runbooks one-per-step, so too small a cap stops it BEFORE it answers.
  // 🔌 createSkillTool / createBashTool / generateIncidentArchive / RUNBOOKS /
  //    SKILLS_DIR are all imported above and waiting for you. The route must stay
  //    the Node runtime (just-bash uses node:fs) — see app/api/chat/route.ts.
  // ───────────────────────────────────────────────────────────────────────────
  return new ToolLoopAgent({
    model: openai(MODEL),
    instructions: SYSTEM_PROMPT,
    // TODO: replace {} with { skill, bash: tools.bash } once you build the toolkit above.
    tools: {},
    stopWhen: stepCountIs(16),
    providerOptions: {
      openai: {
        reasoningSummary: "auto",
        ...(REASONING_EFFORT ? { reasoningEffort: REASONING_EFFORT } : {}),
      },
    },
  });
}

// Constructing the toolkit reads the skills dir and spins up just-bash, so do it
// ONCE per server process and await the same promise on every request.
let agentPromise: Promise<Awaited<ReturnType<typeof buildAgent>>> | undefined;
export function getTriageAgent() {
  return (agentPromise ??= buildAgent());
}

/** The agent's type — the basis for the typed UI message below. */
export type TriageAgent = Awaited<ReturnType<typeof buildAgent>>;

/**
 * End-to-end type safety: the UI message — including the typed `tool-skill` /
 * `tool-bash` parts — is inferred straight from the agent. The client types
 * `useChat` with this via chat-types.ts (which layers on the token-usage metadata
 * the ContextMeter reads).
 */
export type TriageUIMessage = InferAgentUIMessage<TriageAgent>;
